# ---------- Build Stage ----------
FROM maven:3.9.6-eclipse-temurin-17 AS build

WORKDIR /app

# Copy pom first (better caching)
COPY pom.xml .
RUN mvn -q -e -DskipTests dependency:go-offline

# Copy source
COPY src ./src

# Build jar
RUN mvn clean package -DskipTests


# ---------- Run Stage ----------
FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

# Copy jar from build stage
COPY --from=build /app/target/*.jar app.jar
ENV JAVA_TOOL_OPTIONS="-Dio.netty.handler.ssl.noOpenSsl=true -Dio.netty.transport.noNative=true"
# Render provides dynamic PORT
EXPOSE 8080

# Run app
ENTRYPOINT ["java","-jar","/app/app.jar"]